# Generated by Django 3.2.13 on 2022-05-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0003_customer_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpermit",
            name="type",
            field=models.CharField(
                choices=[
                    ("RESIDENT", "Resident permit"),
                    ("COMPANY", "Company permit"),
                ],
                default="RESIDENT",
                max_length=32,
                verbose_name="Type",
            ),
        ),
    ]
