# Generated by Django 3.2.13 on 2022-05-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0004_alter_parkingpermit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("ONLINE_PAYMENT", "Online payment"),
                    ("CASHIER_PAYMENT", "Cashier payment"),
                ],
                default="CASHIER_PAYMENT",
                max_length=50,
                verbose_name="Payment type",
            ),
        ),
    ]
