# Generated by Django 3.2.13 on 2022-06-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0006_update_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("REQUEST_FOR_APPROVAL", "Request for approval"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="OPEN",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
