# Generated by Django 3.2.13 on 2022-06-09 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parking_permits", "0008_alter_refund_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Accepted by",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Accepted at"
            ),
        ),
    ]
