# Generated by Django 3.2.13 on 2022-06-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0009_refund_accepted_time_accepted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpermit",
            name="synced_with_parkkihubi",
            field=models.BooleanField(default=False),
        ),
    ]
